In [1]:
class Set:
	# Creates an empty set instance
	def __init__(self):
		self._theElements = list()

	# Returns the number of items in the set
	def __len__(self):
		return len(self._theElements)

	# Determines if an element is in the set
	def __contains__(self, element):
		return element in self._theElements
    
    # Adds a new unique element to the set
	def add(self, element):
		self._theElements.append(element)

	# Removes an element from the set
	def remove(self, element):
		assert element in self, "The element must be in the set."
		self._theElements.remove(item)

	# Determines if this set is a subset of the other set
	def isSubsetOf(self, setB):
		for element in self:
			if element not in setB:
				return False
		return True

In [2]:
a = Set()

In [3]:
a.add(3)

In [4]:
a.add(5)

In [5]:
a.__contains__(10)

False

In [6]:
from linearset import *

In [7]:
a = Set()

In [8]:
a.add(3)
a.add(4)
a.add(5)
a.add(6)

In [9]:
b = Set()

In [10]:
b.add(3)
b.add(4)
b.add(5)
b.add(6)
b.add(7)

In [11]:
a.isSubsetOf(b)

True

In [12]:
c = a.union(b)

In [13]:
c.__contains__(7)

True

In [14]:
d = Set()
d.add(2)
a.add(3)
a.add(4)
a.add(5)
a.add(6)

In [15]:
d = d.difference(a)

In [16]:
d.__contains__(4)

False

In [17]:
from bubblesort import *

In [18]:
import numpy as np

In [19]:
import random

In [20]:
test = [random.randint(1, 10) for i in range(0,10)]

In [23]:
test = np.arange(0,10)
random.shuffle(test)
test

array([8, 6, 7, 2, 3, 1, 4, 9, 5, 0])

In [24]:
bubbleSort(test)

0 0 

[6 8 7 2 3 1 4 9 5 0]
0 1 

[6 7 8 2 3 1 4 9 5 0]
0 2 

[6 7 2 8 3 1 4 9 5 0]
0 3 

[6 7 2 3 8 1 4 9 5 0]
0 4 

[6 7 2 3 1 8 4 9 5 0]
0 5 

[6 7 2 3 1 4 8 9 5 0]
0 6 

[6 7 2 3 1 4 8 9 5 0]
0 7 

[6 7 2 3 1 4 8 5 9 0]
0 8 

[6 7 2 3 1 4 8 5 0 9]
1 0 

[6 7 2 3 1 4 8 5 0 9]
1 1 

[6 2 7 3 1 4 8 5 0 9]
1 2 

[6 2 3 7 1 4 8 5 0 9]
1 3 

[6 2 3 1 7 4 8 5 0 9]
1 4 

[6 2 3 1 4 7 8 5 0 9]
1 5 

[6 2 3 1 4 7 8 5 0 9]
1 6 

[6 2 3 1 4 7 5 8 0 9]
1 7 

[6 2 3 1 4 7 5 0 8 9]
2 0 

[2 6 3 1 4 7 5 0 8 9]
2 1 

[2 3 6 1 4 7 5 0 8 9]
2 2 

[2 3 1 6 4 7 5 0 8 9]
2 3 

[2 3 1 4 6 7 5 0 8 9]
2 4 

[2 3 1 4 6 7 5 0 8 9]
2 5 

[2 3 1 4 6 5 7 0 8 9]
2 6 

[2 3 1 4 6 5 0 7 8 9]
3 0 

[2 3 1 4 6 5 0 7 8 9]
3 1 

[2 1 3 4 6 5 0 7 8 9]
3 2 

[2 1 3 4 6 5 0 7 8 9]
3 3 

[2 1 3 4 6 5 0 7 8 9]
3 4 

[2 1 3 4 5 6 0 7 8 9]
3 5 

[2 1 3 4 5 0 6 7 8 9]
4 0 

[1 2 3 4 5 0 6 7 8 9]
4 1 

[1 2 3 4 5 0 6 7 8 9]
4 2 

[1 2 3 4 5 0 6 7 8 9]
4 3 

[1 2 3 4 5 0 6 7 8 9]
4 4 

[1 2 3 4 0 5 6 7 8 9]
5 0 

[1 2 3 4 0 5 6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])